apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: sykmelder-statistikk-kafka-unleash-api-token
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: teamsykmelding
  secretName: my-application-unleash-api-token
  environment: {{ unleash_env }}
