apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykmelder-statistikk-kafka
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
  gcp:
    sqlInstances:
      - name: sykmelder-statistikk
        type: POSTGRES_14
        diskSize: 10
        databases:
          - name: statistikk
            envVarPrefix: DB
            users:
              - name: sykmelder-statistikk-next
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 512Mi
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  env:
    - name: SFS_DATA
      value: disykefravar.sfs-data-syk
  accessPolicy:
    outbound:
      external:
        - host: teamsykmelding-unleash-api.nav.cloud.nais.io
  envFrom:
    - secret: sykmelder-statistikk-unleash-api-token
